version: "3.8"

services:
  savagescan-db:
    container_name: savagescan-db
    image: postgres:14.4-alpine
    restart: always
    expose:
      - "${SPRING_DATASOURCE_PORT}"
    ports:
      - ${SPRING_DATASOURCE_PORT}:${SPRING_DATASOURCE_PORT}
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DATABASE}
      - POSTGRES_USER=${SPRING_DATASOURCE_USER}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    command: -p ${SPRING_DATASOURCE_PORT}
  savagescan-vpn:
    image: azinchen/nordvpn:latest
    container_name: savagescan-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USER}
      - PASS=${NORDVPN_PASSWORD}
      - GROUP=Europe
      - RANDOM_TOP=10
    restart: always
  savagescan-service:
    container_name: savagescan-service
    network_mode: service:savagescan-vpn
    ports:
      - "9010:9010"
    depends_on:
      - savagescan-db
      - savagescan-vpn
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

volumes:
  postgres:
    driver: local
