version: "3.8"

services:
  savagescan-db:
    container_name: savagescan-db
    image: postgres:14.4-alpine
    network_mode: bridge
    restart: always
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DATABASE}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    command: -p ${SPRING_DATASOURCE_PORT}
  savagescan-vpn:
    image: azinchen/nordvpn:latest
    container_name: savagescan-vpn
    network_mode: bridge
    ports:
      - "9010:9010"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USER}
      - PASS=${NORDVPN_PASSWORD}
      - GROUP=Europe
      - COUNTRY=125
      - RANDOM_TOP=10
    restart: always
    links:
      - savagescan-db
  savagescan-service:
    container_name: savagescan-service
    network_mode: service:savagescan-vpn
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://savagescan-db:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - savagescan-db
      - savagescan-vpn
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

volumes:
  postgres:
    driver: local
