version: "3.8"

services:
  savagescan-db:
    container_name: savagescan-db
    image: postgres:14.4-alpine
    restart: always
    expose:
      - "${SPRING_DATASOURCE_PORT}"
    networks:
      - proxy
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DATABASE}
      - POSTGRES_USER=${SPRING_DATASOURCE_USER}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    command: -p ${SPRING_DATASOURCE_PORT}
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.tcp.tls=true'
      - 'traefik.tcp.routers.savagescan-db.rule=HostSNI(`*`)'
      - 'traefik.tcp.services.savagescan-db.loadbalancer.server.port=${SPRING_DATASOURCE_PORT}'
      - 'traefik.tcp.routers.savagescan-db.entrypoints=savagescan-db'
      - 'traefik.tcp.routers.savagescan-db.service=savagescan-db'
  savagescan-service:
    container_name: savagescan-service
    ports:
      - 9010:9010
    depends_on:
      - savagescan-db
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy

volumes:
  postgres:
    driver: local

networks:
  proxy:
    external: false
    name: proxy
