name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo SPRING_DATASOURCE_HOST=${{ secrets.SPRING_DATASOURCE_HOST }} >> .env
          echo SPRING_DATASOURCE_PORT=${{ secrets.SPRING_DATASOURCE_PORT }} >> .env
          echo SPRING_DATASOURCE_DATABASE=${{ secrets.SPRING_DATASOURCE_DATABASE }} >> .env
          echo SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} >> .env
          echo SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} >> .env

          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
          
          echo NORDVPN_USER=${{ secrets.NORDVPN_USER }} >> .env
          echo NORDVPN_PASSWORD=${{ secrets.NORDVPN_PASSWORD }} >> .env
          cat .env

      - name: Docker run
        run: docker-compose up -d --force-recreate --build

      - name: remove unused images, containers, volumes, and networks
        run: docker image prune -a -f --filter "until=24h" && docker container prune -f --filter "until=24h" && docker volume prune -f && docker network prune -f --filter "until=24h"

